function Home(){
    return <div className="home">
        <h1>Welcome</h1>
        <p>Welcome to our platform! We are thrilled to have you join us on this exciting journey. Whether you're a job seeker looking for new opportunities or an employer seeking talented individuals, we've got you covered. Our platform serves as a bridge, connecting job seekers with employers and facilitating the process of finding the perfect match. With our intuitive job router built using React, navigating through our extensive job listings and company profiles is a breeze.</p>
        <p>At our core, we believe in the power of technology to transform the way we approach job search and recruitment.Our job router in React is just one example of how we harness the latest web development technologies to deliver a seamless and user-friendly experience. By simplifying the process of job search and recruitment, we strive to empower both job seekers and employers, fostering meaningful connections and facilitating career growth.</p>
        <p>With our comprehensive job router, you can explore a vast array of job opportunities across various industries and sectors. Whether you're looking for full-time positions, part-time gigs, or remote work options, our platform offers a diverse range of job listings to cater to your specific needs. Our job router allows you to easily navigate through different categories, search for specific roles or keywords, and filter results based on location, salary, and other criteria. Say goodbye to endless scrolling and tedious searches, and say hello to a streamlined and efficient job search experience.</p>
        <p>For employers, our job router simplifies the process of posting job openings and finding qualified candidates. You can create detailed company profiles, showcase your company culture and values, and attract top talent from our pool of job seekers. With our integrated applicant tracking system, managing applications and communicating with candidates has never been easier. Our goal is to provide employers with the tools they need to identify and connect with the best-fit candidates efficiently, saving time and resources in the recruitment process.We're excited to have you join our platform and experience the benefits of our job router in React. Get started today and unlock a world of opportunities or find your ideal candidate with just a few clicks. Together, let's redefine the way we approach job search and recruitment in the digital age.</p>
    </div>
}
 
export default Home